CREATE TABLE SABOR 
(
  NOME VARCHAR2(100) NOT NULL 
, CONSTRAINT SABOR_PK PRIMARY KEY 
  (
    NOME 
  )
  ENABLE 
);

CREATE TABLE CALDA 
(
  NOME VARCHAR2(100) NOT NULL 
, CONSTRAINT CALDA_PK PRIMARY KEY 
  (
    NOME 
  )
  ENABLE 
);

CREATE TABLE PEDIDO 
(
  ID NUMBER NOT NULL 
, NOME_CLIENTE VARCHAR2(100) NOT NULL 
, DATA_PEDIDO DATE NOT NULL 
, CONSTRAINT PEDIDO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE SORVETE 
(
  ID NUMBER NOT NULL 
, ID_PEDIDO NUMBER NOT NULL 
, ID_SABOR VARCHAR2(100) NOT NULL 
, ID_CALDA VARCHAR2(100) 
, QTD_BOLAS NUMBER NOT NULL 
, CONSTRAINT SORVETE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE SORVETE
ADD FOREIGN KEY (ID_PEDIDO) 
REFERENCES PEDIDO(ID);

ALTER TABLE SORVETE
ADD FOREIGN KEY (ID_SABOR) 
REFERENCES SABOR(NOME);

ALTER TABLE SORVETE
ADD FOREIGN KEY (ID_CALDA) 
REFERENCES CALDA(NOME);

INSERT INTO CALDA(NOME) VALUES('Chocolate');
/
INSERT INTO CALDA(NOME) VALUES('Morando');
/
INSERT INTO CALDA(NOME) VALUES('Leite Condensado');
/
INSERT INTO CALDA(NOME) VALUES('Uva');
/
INSERT INTO CALDA(NOME) VALUES('Macaiba');
/
INSERT INTO CALDA(NOME) VALUES('Pitomba');

INSERT INTO SABOR(NOME) VALUES('Chocolate');
/
INSERT INTO SABOR(NOME) VALUES('Morango');
/
INSERT INTO SABOR(NOME) VALUES('Flocos');
/
INSERT INTO SABOR(NOME) VALUES('Tomate');
/
INSERT INTO SABOR(NOME) VALUES('Pistaxiiiiiii');

CREATE SEQUENCE S_PEDIDO INCREMENT BY 1 START WITH 1 MAXVALUE 99999 MINVALUE 1;
CREATE SEQUENCE S_SORVETE INCREMENT BY 1 START WITH 1 MAXVALUE 99999 MINVALUE 1;
